name: 'Manually Cherry-Pick to Release Branches'

on:
  workflow_dispatch:
    inputs:
      merge_commit_sha:
        description: 'The sha of the merge commit from the main PR.'
        required: true

env :
  TERRAFORM_MAINTAINERS: '["matttrach"]'

jobs:
  create-cherry-pick-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write
    steps:
      - name: 'Wait for merge to settle'
        # https://github.com/actions/github-script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          MERGE_COMMIT_SHA: ${{ inputs.merge_commit_sha }}
          TERRAFORM_MAINTAINERS: ${{ env.TERRAFORM_MAINTAINERS }}
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const mergeCommitSha = process.env.MERGE_COMMIT_SHA;
            // wait 10 seconds to allow GitHub to index the commit and associated PRs
            await new Promise(resolve => setTimeout(resolve, 10000));
            // just in case the GitHub API is still having trouble, try to fetch associated PRs
            let response;
            try {
                response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner,
                repo,
                commit_sha: mergeCommitSha
              });
            } catch (error) {
              core.setFailed(`Failed to retrieve PRs associated with commit ${mergeCommitSha}: ${error.message}`);
            }
      - name: 'Checkout Repository'
        # https://github.com/actions/checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: 'main'
      - name: 'Find Issues and Create Cherry-Pick PRs'
        # https://github.com/actions/github-script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          MERGE_COMMIT_SHA: ${{ inputs.merge_commit_sha }}
          TERRAFORM_MAINTAINERS: ${{ env.TERRAFORM_MAINTAINERS }}
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/backport-pr.js`;
            const { default: script } = await import(scriptPath);
            await script({github, core, process});
