name: 'Auto Cherry-Pick to Release Branches'

on:
  push:
    branches:
      - 'main'

env :
  TERRAFORM_MAINTAINERS: '["matttrach"]'

jobs:
  create-cherry-pick-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write

    steps:
      - name: 'Wait for merge to settle'
        id: wait_for_settle
        # https://github.com/actions/github-script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TERRAFORM_MAINTAINERS: ${{ env.TERRAFORM_MAINTAINERS }}
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const mergeCommitSha = context.payload.head_commit.id;
            // wait 10 seconds to allow GitHub to index the commit and associated PRs
            await new Promise(resolve => setTimeout(resolve, 10000));
            // just in case the GitHub API is still having trouble, try to fetch associated PRs
            try {
              const { data: associatedPrs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner,
                repo,
                commit_sha: mergeCommitSha
              });
            } catch (error) {
              core.setFailed(`Failed to retrieve PRs associated with commit ${mergeCommitSha}: ${error.message}`);
            }
            // set output for next steps
            core.setOutput('merge_commit_sha', mergeCommitSha);
      - name: 'Checkout Repository'
        # https://github.com/actions/checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          ref: 'main'
      - name: 'Find Issues and Create Cherry-Pick PRs'
        # https://github.com/actions/github-script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TERRAFORM_MAINTAINERS: ${{ env.TERRAFORM_MAINTAINERS }}
          MERGE_COMMIT_SHA: ${{ steps.wait_for_settle.outputs.merge_commit_sha }}
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/backport-pr.js`;
            const { default: script } = await import(scriptPath);
            await script({github, core, process});
