name: Manually Create Full Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create, make sure to select the main branch.'
        required: true
      sha:
        description: 'The commit SHA to create the tag from, defaults to HEAD of the selected branch.'
        required: false

permissions: {}

jobs:
  release:
    name: 'Full Release'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write
      actions: read
    steps:
      - name: 'Checkout Repository'
        id: checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: 'Check User In Maintainers'
        id: check-user-in-maintainers
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TERRAFORM_MAINTAINERS: '["matttrach"]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/check-maintainer.js`;
            const { default: script } = await import(scriptPath);
            return await script({github, context, core, process});
      - name: 'Validate Release Tag'
        id: validate-release-tag
        env:
          TAG: ${{ inputs.tag }}
          EXPECTED_TYPE: release
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/validate-tag.sh
      - name: 'Create and Push Tag'
        id: create-push-tag
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TAG: ${{ inputs.tag }}
          SHA: ${{ inputs.sha || github.sha }}
          CREATE_REF: 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/create-push-tag.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
      - name: 'Checkout New Tag'
        id: checkout-new-tag
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ steps.create-push-tag.outputs.tag }}
          path: tags/${{ steps.create-push-tag.outputs.tag }}
          fetch-depth: 0
      - name: 'Prepare Release Directory'
        id: prepare-release-dir
        env:
          WORKSPACE: ${{ github.workspace }}
          TAG: ${{ steps.create-push-tag.outputs.tag }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/prepare-release-dir.sh
      - name: 'Retrieve GPG Credentials'
        id: retrieve-gpg-credentials
        # https://github.com/rancher-eio/read-vault-secrets/commits
        uses: rancher-eio/read-vault-secrets@dfae8acd43a9e170fca5f90168da22f814fe4e9a # @main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/signing/gpg passphrase | GPG_PASSPHRASE ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKeyId | GPG_KEY_ID ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKey | GPG_KEY
      - name: 'Setup Go'
        id: setup-go
        # https://github.com/actions/setup-go/releases
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: tags/${{ steps.create-push-tag.outputs.tag }}/go.mod
          cache-dependency-path: tags/${{ steps.create-push-tag.outputs.tag }}/go.sum
          cache: true
      - name: 'Run GoReleaser'
        id: run-goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          GPG_KEY: ${{ env.GPG_KEY }}
          TAG: ${{ steps.create-push-tag.outputs.tag }}
          WORKING_DIR: ${{ github.workspace }}/tags/${{ steps.create-push-tag.outputs.tag }}
          SKIP_VALIDATE: true
          GORELEASER_CONFIG: ../../.goreleaser_manual.yml
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/goreleaser.sh
      - name: 'Publish Release'
        id: publish-release
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          VERSION: ${{ steps.create-push-tag.outputs.tag }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/publish-release.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
