name: Manually Create RC Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch where the sha exists.'
        required: true
        default: 'main'
      sha:
        description: 'The commit SHA to create the tag from, defaults to HEAD of the selected branch.'
        required: false
      tag:
        description: 'The rc tag to create, e.g. v1.2.3-rc.1'
        required: true

permissions: {}

jobs:
  rc-release:
    name: 'RC Release'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      actions: read
    steps:
      - name: 'Check User In Maintainers'
        id: check-user-in-maintainers
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TERRAFORM_MAINTAINERS: '["matttrach"]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `.github/workflows/scripts/check-maintainer.js`;
            const { default: script } = await import(scriptPath);
            return await script({github, context, core, process});
      - name: 'Validate RC Tag'
        id: validate-rc-tag
        env:
          TAG: ${{ inputs.tag }}
          EXPECTED_TYPE: rc
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/validate-tag.sh
      - name: 'Checkout Repository'
        id: checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Create and Push RC Tag via API
        id: create-push-rc-tag
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TAG: ${{ inputs.tag }}
          SHA: ${{ inputs.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `.github/workflows/scripts/create-push-tag.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
      - name: 'Checkout New Tag'
        id: checkout-new-tag
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.tag }}
          path: tags/${{ inputs.tag }}
      - name: 'Prepare Release Directory'
        id: prepare-release-dir
        env:
          WORKSPACE: ${{ github.workspace }}
          TAG: ${{ inputs.tag }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/prepare-release-dir.sh
      - name: 'Retrieve GPG Credentials'
        id: retrieve-gpg-credentials
        # https://github.com/rancher-eio/read-vault-secrets/commits
        uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # @main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/signing/gpg passphrase | GPG_PASSPHRASE ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKeyId | GPG_KEY_ID ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKey | GPG_KEY
      - name: 'Import GPG Key'
        id: import-gpg-key
        env:
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_KEY: ${{ env.GPG_KEY }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/import-gpg-key.sh
      - name: 'Setup Go'
        id: setup-go
        # https://github.com/actions/setup-go/releases
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ./tags/${{ inputs.tag }}/go.mod
          cache-dependency-path: ./tags/${{ inputs.tag }}/go.sum
          cache: true
      - name: 'Run GoReleaser'
        id: run-goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          TAG: ${{ inputs.tag }}
          WORKING_DIR: ${{ github.workspace }}/tags/${{ inputs.tag }}
          SKIP_VALIDATE: true
          GORELEASER_CONFIG: ../../.goreleaser_rc.yml
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/run-goreleaser.sh
      - name: 'Publish RC'
        id: publish-rc
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          VERSION: ${{ inputs.tag }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `.github/workflows/scripts/publish-release.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
