name: Manually Create Full Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create, make sure to select the correct branch.'
        required: true
      sha:
        description: 'The commit SHA to create the tag from, defaults to HEAD of the selected branch.'
        required: false

permissions: {}

jobs:
  release:
    name: 'Full Release'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write
      actions: read
    steps:
      - name: 'Check User In Maintainers'
        id: check-user-in-maintainers
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TERRAFORM_MAINTAINERS: '["matttrach"]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `.github/workflows/scripts/check-maintainer.js`;
            const { default: script } = await import(scriptPath);
            return await script({github, context, core, process});
      - name: 'Validate Release Tag'
        id: validate-release-tag
        env:
          TAG: ${{ inputs.tag }}
          EXPECTED_TYPE: release
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/validate-tag.sh
      - name: 'Checkout Repository'
        id: checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: 'Create and Push Tag with Git'
        id: create-push-tag
        env:
          TAG: ${{ inputs.tag }}
          SHA: ${{ inputs.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/manual-create-push-tag.sh
      - name: 'Checkout New Tag'
        id: checkout-new-tag
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.tag }}
          path: tags/${{ inputs.tag }}
      - name: 'Prepare Release Directory'
        id: prepare-release-dir
        env:
          WORKSPACE: ${{ github.workspace }}
          TAG: ${{ inputs.tag }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/prepare-release-dir.sh
      - name: 'Retrieve GPG Credentials'
        id: retrieve-gpg-credentials
        # https://github.com/rancher-eio/read-vault-secrets/commits
        uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # @main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/signing/gpg passphrase | GPG_PASSPHRASE ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKeyId | GPG_KEY_ID ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKey | GPG_KEY
      - name: 'Import GPG Key'
        id: import-gpg-key
        env:
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_KEY: ${{ env.GPG_KEY }}
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/import-gpg-key.sh
      - name: 'Setup Go'
        id: setup-go
        # https://github.com/actions/setup-go/releases
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: tags/${{ inputs.tag }}/go.mod
          cache-dependency-path: tags/${{ inputs.tag }}/go.sum
          cache: true
      - name: 'Run GoReleaser'
        id: run-goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          TAG: ${{ inputs.tag }}
          WORKING_DIR: ${{ github.workspace }}/tags/${{ inputs.tag }}
          SKIP_VALIDATE: true
          GORELEASER_CONFIG: ../../.goreleaser.yml
        run: .github/workflows/scripts/nix-run.sh bash .github/workflows/scripts/run-goreleaser.sh
      - name: 'Publish Release'
        id: publish-release
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          VERSION: ${{ inputs.tag }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = `.github/workflows/scripts/publish-release.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
