name: pull_request_review_trigger

on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  trigger:
    name: 'Trigger Executor on Event'
    if: |
      github.event.issue.pull_request && (
        (startsWith(github.event.comment.body, '/merge') && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)) ||
        (contains(github.event.comment.body, 'and generated no new comments.') && github.event.comment.user.login == 'github-actions[bot]')
      )
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout Repository
        id: checkout-repository
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: 'main'

      - name: Log Successful Trigger
        env:
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
          EVENT_NAME: ${{ github.event_name }}
        run: .github/workflows/scripts/log-trigger.sh
